function escapeHtml(value) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}

function flightAlertTemplate(match) {
    const data = {
        hexCode: escapeHtml(match.hexCode || "Unknown"),
        registration: escapeHtml(match.registration || "Unknown"),
        aircraftType: escapeHtml(match.aircraftType || "Unknown"),
        operator: escapeHtml(match.operator || "Unknown"),
        altitude: escapeHtml(match.altitude ?? "Unknown"),
        groundAltitude: escapeHtml(match.groundAltitude || "Unknown"),
        speed: escapeHtml(match.speed ?? "Unknown"),
        track: escapeHtml(match.track ?? "Unknown"),
        squawk: escapeHtml(match.squawk ?? "Unknown"),
        latitude: escapeHtml(match.latitude ?? "Error fetching latitude"),
        longitude: escapeHtml(match.latitude ?? "Error fetching longitude"),
        country: escapeHtml(match.country ?? "Error fetching country"),
        cMessages: escapeHtml(match.cMessages ?? "Error fetching cMessages"),
        time: escapeHtml(
            new Date().toISOString().replace("T", " ").replace("Z", " UTC")
        )
    };

    return `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Falcon Intelligence</title>
</head>

<body style="
    margin:0;
    padding:0;
    background:#071018;
    font-family:'Segoe UI',Arial,sans-serif;
    color:#ffffff;
">

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#071018;padding:40px 16px;">
<tr>
<td align="center">

<table role="presentation"
width="100%"
cellpadding="0"
cellspacing="0"
style="
max-width:760px;
background:#0b1620;
border:1px solid #183743;
border-radius:16px;
overflow:hidden;
box-shadow:0 20px 50px rgba(0,0,0,.45);
">

<!-- ================= HEADER ================= -->

<tr>
<td
style="
background:linear-gradient(135deg,#071822 0%,#0c2431 45%,#10322e 100%);
padding:42px 30px;
border-bottom:1px solid #214654;
text-align:center;
">

<div
style="
display:inline-block;
padding:7px 18px;
border:1px solid #2c6973;
border-radius:999px;
color:#5eead4;
font-size:11px;
letter-spacing:2px;
margin-bottom:18px;
">
TACTICAL AIR SURVEILLANCE NETWORK
</div>

<h1
style="
margin:0;
font-size:34px;
letter-spacing:4px;
font-weight:700;
color:#ffffff;
">
FALCON INTELLIGENCE
</h1>

<p
style="
margin:14px 0 0;
font-size:15px;
letter-spacing:1px;
color:#8bd3ff;
">
AUTOMATED FLIGHT DETECTION & ALERT SYSTEM
</p>

</td>
</tr>

<!-- ================= BODY ================= -->

<tr>
<td style="padding:34px;">

<h2
style="
margin:0;
color:#5eead4;
font-size:24px;
letter-spacing:1px;
">
Aircraft Detected Within Surveillance Radius
</h2>

<p
style="
margin-top:18px;
color:#c8d4db;
line-height:1.8;
font-size:15px;
">
A monitored aircraft has entered the configured surveillance radius of
<strong style="color:#5eead4;">100 km surrounding Vadodara, Gujarat</strong>.
This notification has been automatically generated by the Falcon Intelligence
monitoring engine.
</p>

<!-- ================= STATUS ================= -->

<table
role="presentation"
width="100%"
cellpadding="0"
cellspacing="0"
style="
margin-top:30px;
background:#08131a;
border:1px solid #214654;
border-radius:10px;
overflow:hidden;
font-family:Consolas,'Courier New',monospace;
">

<tr>
<td
style="
padding:14px 18px;
background:#0f2430;
color:#67e8f9;
font-size:13px;
letter-spacing:2px;
font-weight:bold;
">
MISSION STATUS
</td>
</tr>

<tr>
<td style="padding:20px;color:#d8f6ff;font-size:14px;line-height:2;">

STATUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:
<span style="color:#22c55e;">TRACK ACTIVE</span><br>

ZONE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:
VADODARA<br>

RADIUS&nbsp;&nbsp;&nbsp;&nbsp;:
100 KM<br>

SOURCE&nbsp;&nbsp;&nbsp;&nbsp;:
ADS-B<br>

TIME (UTC)&nbsp;:
${data.time}

</td>
</tr>

</table>

<!-- ================= TELEMETRY ================= -->

<table
role="presentation"
width="100%"
cellpadding="0"
cellspacing="0"
style="
margin-top:30px;
border-collapse:collapse;
background:#08131a;
border:1px solid #214654;
font-family:Consolas,'Courier New',monospace;
">

<tr style="background:#0f2430;">
<td colspan="2"
style="
padding:14px 18px;
color:#67e8f9;
font-size:13px;
letter-spacing:2px;
font-weight:bold;
">
AIRCRAFT TELEMETRY
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;width:42%;">
Registration
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;font-weight:bold;">
${data.registration}
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;">
Aircraft Type
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;">
${data.aircraftType}
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;">
Operator
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;">
${data.operator}
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;">
ICAO HEX
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;">
${data.hexCode}
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;">
Altitude
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;">
${data.altitude} ft
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;">
Ground Speed
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;">
${data.speed} knots
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;border-bottom:1px solid #17313c;">
Track
</td>
<td style="padding:12px 18px;color:#ffffff;border-bottom:1px solid #17313c;">
${data.track}&deg;
</td>
</tr>

<tr>
<td style="padding:12px 18px;color:#7ea4b3;">
Squawk
</td>
<td style="padding:12px 18px;color:#ffffff;font-weight:bold;">
${data.squawk}
</td>
</tr>

</table>

<!-- ================= ALERT BOX ================= -->

<div
style="
margin-top:32px;
background:#08151d;
border:1px solid #214654;
border-left:5px solid #22c55e;
border-radius:10px;
padding:20px;
">

<div
style="
font-size:12px;
letter-spacing:2px;
font-weight:bold;
color:#22c55e;
margin-bottom:12px;
">
ALERT STATUS
</div>

<div
style="
color:#d9e8ef;
font-size:15px;
line-height:1.8;
">
The monitored aircraft is currently operating inside the configured
surveillance perimeter around Vadodara.

Continue monitoring for changes in heading, altitude, speed or departure from
the monitored zone.
</div>

</div>

</td>
</tr>

<!-- ================= FOOTER ================= -->

<tr>
<td
style="
background:#050d13;
padding:28px;
text-align:center;
border-top:1px solid #17313c;
">

<p
style="
margin:0;
color:#5eead4;
font-size:13px;
letter-spacing:3px;
">
FALCON INTELLIGENCE
</p>

<p
style="
margin:10px 0 0;
color:#7c95a1;
font-size:12px;
letter-spacing:1px;
">
TACTICAL FLIGHT MONITORING • AUTOMATED ALERT DELIVERY
</p>

<p
style="
margin-top:18px;
color:#4d6572;
font-size:11px;
">
© ${new Date().getFullYear()} Falcon Intelligence. All rights reserved.
</p>

</td>
</tr>

</table>

</td>
</tr>
</table>

</body>
</html>
`;
}

module.exports = flightAlertTemplate;